"""add breakpoint and accessibility_report to scans

Revision ID: 1d2ce495ba8c
Revises: 41e18a3bd5ba
Create Date: 2026-08-16 15:37:54.908870

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d2ce495ba8c"
down_revision: str | Sequence[str] | None = "41e18a3bd5ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scans", sa.Column("breakpoint", sa.String(), nullable=True))
    op.add_column(
        "scans",
        sa.Column("accessibility_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scans", "accessibility_report")
    op.drop_column("scans", "breakpoint")
    # ### end Alembic commands ###
