"""add fix_review to design_analyses

Revision ID: 36540515d990
Revises: 791a1f0cde3a
Create Date: 2026-09-03 11:07:01.957810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36540515d990'
down_revision: Union[str, Sequence[str], None] = '791a1f0cde3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_analyses', sa.Column('fix_review', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_analyses', 'fix_review')
    # ### end Alembic commands ###
