"""add visual comparison fields to design_analyses

Revision ID: 5ee4ee840844
Revises: e440743b094a
Create Date: 2026-08-18 19:23:00.732151

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ee4ee840844"
down_revision: str | Sequence[str] | None = "e440743b094a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "design_analyses",
        sa.Column("comparison_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("design_analyses", sa.Column("diff_image_key", sa.String(), nullable=True))
    op.add_column(
        "design_analyses",
        sa.Column("visual_comparison", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("design_analyses", "visual_comparison")
    op.drop_column("design_analyses", "diff_image_key")
    op.drop_column("design_analyses", "comparison_result")
    # ### end Alembic commands ###
