"""add accessibility fields to design_analyses

Revision ID: 73f4e150950f
Revises: 5ee4ee840844
Create Date: 2026-08-18 19:46:27.216065

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73f4e150950f"
down_revision: str | Sequence[str] | None = "5ee4ee840844"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "design_analyses",
        sa.Column("accessibility_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "design_analyses",
        sa.Column(
            "accessibility_interpretation", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("design_analyses", "accessibility_interpretation")
    op.drop_column("design_analyses", "accessibility_report")
    # ### end Alembic commands ###
