"""add fix_proposal to design_analyses

Revision ID: 791a1f0cde3a
Revises: e9edcbbce631
Create Date: 2026-08-29 14:52:11.959963

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "791a1f0cde3a"
down_revision: str | Sequence[str] | None = "e9edcbbce631"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "design_analyses",
        sa.Column("fix_proposal", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("design_analyses", "fix_proposal")
    # ### end Alembic commands ###
