"""add verification to design_analyses

Revision ID: 7b9e7df72632
Revises: a7b56430e596
Create Date: 2026-09-03 15:59:47.662420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b9e7df72632'
down_revision: Union[str, Sequence[str], None] = 'a7b56430e596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_analyses', sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('design_analyses', sa.Column('verification_screenshot_key', sa.String(), nullable=True))
    op.add_column('design_analyses', sa.Column('verification_diff_image_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_analyses', 'verification_diff_image_key')
    op.drop_column('design_analyses', 'verification_screenshot_key')
    op.drop_column('design_analyses', 'verification')
    # ### end Alembic commands ###
