"""add aggregated_findings to design_analyses

Revision ID: 9fc6726e95a8
Revises: 73f4e150950f
Create Date: 2026-08-18 20:21:05.127853

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fc6726e95a8"
down_revision: str | Sequence[str] | None = "73f4e150950f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "design_analyses",
        sa.Column("aggregated_findings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("design_analyses", "aggregated_findings")
    # ### end Alembic commands ###
