"""add source_path and code_analysis for code analysis agent

Revision ID: a7505a6aa4dc
Revises: 9fc6726e95a8
Create Date: 2026-08-19 15:21:10.074414

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7505a6aa4dc"
down_revision: str | Sequence[str] | None = "9fc6726e95a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "design_analyses",
        sa.Column("code_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("projects", sa.Column("source_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "source_path")
    op.drop_column("design_analyses", "code_analysis")
    # ### end Alembic commands ###
