"""add fix_application to design_analyses

Revision ID: a7b56430e596
Revises: 36540515d990
Create Date: 2026-09-03 11:30:35.146890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7b56430e596'
down_revision: Union[str, Sequence[str], None] = '36540515d990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_analyses', sa.Column('fix_application', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_analyses', 'fix_application')
    # ### end Alembic commands ###
