"""add target_selector to projects

Revision ID: bd8b27e4759e
Revises: 1e668ba6d8de
Create Date: 2026-08-15 21:29:18.088573

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd8b27e4759e"
down_revision: str | Sequence[str] | None = "1e668ba6d8de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("target_selector", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "target_selector")
    # ### end Alembic commands ###
