"""add production_screenshot_key to design_analyses

Revision ID: e440743b094a
Revises: db8291f550e8
Create Date: 2026-08-18 14:40:23.578588

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e440743b094a"
down_revision: str | Sequence[str] | None = "db8291f550e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "design_analyses", sa.Column("production_screenshot_key", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("design_analyses", "production_screenshot_key")
    # ### end Alembic commands ###
