"""Output contracts for Design Drift's own LangGraph agents (see
docs/architecture.md's runtime-agent table) — one per agent, grown here as
each vertical slice lands, same as app.graph.state.

Most of these are *structured-output* contracts: their `Field(description=...)`
text is part of the JSON schema the LLM is constrained to, so it's written
for the model to read (see app.integrations.llm.client). The aggregation
types at the bottom are the exception — they're built deterministically in
Python, never generated by a model, so they use plain comments instead.

Distinct from app.integrations.llm.types.VisualReviewResult: that's the
Visual Comparison Agent's job (Figma vs. production, judging drift), kept
in the integrations package since app.services.reviews (its pre-graph,
Scan-scoped predecessor) already depended on it before this package
existed. Design Analysis only ever sees the Figma side — it interprets
structure and intent before any production capture exists, so a later
Visual Comparison pass knows what to compare against, and a later Code
Analysis / Fix Agent pass knows what's risky to get wrong.
"""

from enum import StrEnum

from pydantic import BaseModel, Field


class DesignComponent(BaseModel):
    name: str = Field(
        description="Short name for this component/region, e.g. 'primary CTA button'."
    )
    role: str = Field(description="This component's apparent purpose within the design.")
    notable_styling: str = Field(
        description=(
            "Key style choices worth preserving in an implementation: colors, spacing, "
            "typography, alignment, etc."
        )
    )


class DesignAnalysisResult(BaseModel):
    layout_summary: str = Field(
        description="Plain-language summary of the overall layout and structure."
    )
    design_intent: str = Field(
        description=(
            "What this design is trying to achieve for the user — its apparent purpose and "
            "priorities."
        )
    )
    key_components: list[DesignComponent] = Field(
        default_factory=list,
        description=(
            "The most important distinct components/regions in this design, ordered by "
            "visual prominence."
        ),
    )
    implementation_risks: list[str] = Field(
        default_factory=list,
        description=(
            "Aspects of this design that are easy to get subtly wrong when implementing in "
            "code — precise spacing, a non-obvious layout technique, responsive behavior that "
            "isn't visible in a single static render, and so on. Flagged so a later comparison "
            "pass knows what to scrutinize most closely."
        ),
    )


class AccessibilityPriority(StrEnum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class AccessibilityIssue(BaseModel):
    violation_id: str = Field(
        description="The axe-core violation `id` (see AxeViolation) this issue refers to."
    )
    user_impact: str = Field(
        description=(
            "Plain-language explanation of how this actually affects real users trying to use "
            "the page — not a restatement of the rule name."
        )
    )
    priority: AccessibilityPriority = Field(
        description=(
            "Your own triage call for how urgently this deserves attention. May differ from "
            "axe-core's own `impact` rating: axe rates a rule in the abstract, this should "
            "account for where on the page it appears and how it's likely to be encountered."
        )
    )


class AccessibilityInterpretation(BaseModel):
    summary: str = Field(
        description="One-paragraph, plain-language summary of the page's accessibility posture."
    )
    most_important_issues: list[AccessibilityIssue] = Field(
        default_factory=list,
        description=(
            "Which violations most deserve attention first, ordered most urgent first — not "
            "necessarily every violation, just the ones worth specifically calling out."
        ),
    )


# --- Aggregation (deterministic; see this module's docstring) ---


class FindingSource(StrEnum):
    """Which agent produced a finding — kept so the merged list stays
    traceable back to the agent (and raw output) it came from.
    """

    VISUAL_COMPARISON = "visual_comparison"
    ACCESSIBILITY = "accessibility"


class FindingPriority(StrEnum):
    """Shared triage scale, so findings from different agents can sit in
    one ordered list.

    Deliberately *urgency*, matching AccessibilityPriority's existing
    semantics one-to-one. Visual findings are mapped in from
    FindingSeverity, which measures something subtly different (how wrong
    it looks, not how urgently to fix) — see _VISUAL_SEVERITY_TO_PRIORITY
    in app.agents.aggregate_findings. That mapping is many-to-one and so
    lossy, which is why AggregatedFinding keeps the agent's own original
    wording alongside it.
    """

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class AggregatedFinding(BaseModel):
    source: FindingSource
    priority: FindingPriority
    # The producing agent's own severity/priority word ("critical",
    # "cosmetic", "high", ...), preserved verbatim so normalizing onto
    # FindingPriority above coarsens only the sort key, never the record.
    original_severity: str
    title: str
    detail: str
    # Visual findings may name the UI area responsible; accessibility
    # findings don't (axe-core's own element targets stay in the raw
    # AccessibilityReport rather than being flattened to a string here).
    likely_area: str | None = None


class AggregatedFindings(BaseModel):
    """Every agent's findings merged into one triaged list.

    This is the workflow's answer to "what did we actually find?" — the
    input a later Code Analysis / Fix Agent pass consumes, and the branch
    point docs/architecture.md's flow calls `route: problems found?`.
    """

    problems_found: bool
    # Ordered highest-priority first; ties keep each agent's own ordering.
    findings: list[AggregatedFinding] = []


class LocationConfidence(StrEnum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class SourceLocation(BaseModel):
    file_path: str = Field(
        description=(
            "The path, copied exactly from one of the candidates you were shown. Never invent "
            "a path, and never name a file that wasn't among the candidates."
        )
    )
    line_start: int = Field(
        description=(
            "First line of the responsible code. Use the line numbers shown in the snippet — "
            "they are the real line numbers in that file."
        )
    )
    line_end: int = Field(
        description="Last line of the responsible code. Same as line_start for a single line."
    )
    code_evidence: str = Field(
        description=(
            "The exact lines from the snippet that justify this location, copied verbatim. "
            "This is what a human will check first, so it must actually appear in the snippet."
        )
    )


class FindingLocation(BaseModel):
    finding_title: str = Field(
        description="The finding's title, copied exactly from the findings list you were given."
    )
    no_match: bool = Field(
        description=(
            "True when the candidates don't contain convincing evidence for this finding. "
            "Saying so is a correct, useful answer — much better than pointing a developer at "
            "a location you don't actually believe in."
        )
    )
    location: SourceLocation | None = Field(
        default=None,
        description="The single most likely location. Must be null when no_match is true.",
    )
    explanation: str = Field(
        description=(
            "Why this location causes the finding — or, when no_match is true, what was "
            "missing from the evidence."
        )
    )
    confidence: LocationConfidence = Field(
        description=(
            "How confident you are in this location. Reserve 'high' for when the snippet "
            "directly shows the responsible markup or style rule."
        )
    )


class CodeAnalysisResult(BaseModel):
    summary: str = Field(
        description=(
            "One short paragraph on how well these findings map onto the codebase overall, "
            "including anything that made the mapping hard."
        )
    )
    locations: list[FindingLocation] = Field(
        default_factory=list,
        description="One entry per finding you were given, in the same order.",
    )
